# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d308a299427e403696f25889704c80c8631200db183725dbf833074c7272aa3e5a8bf8d6acbe93400bca62737e75c39d8198348531badf2976bc79f644fbaff3

test:
  secret_key_base: b8c463d24c88207dc31fcd464a55c94a6c86a82a3464384e6a07a6933f2c9d4b4b36991d7c1cac269434b44fa2c7dadbb573b651ed10bd5e0bdc8a1e356d091d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
